"""create initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 11:35:21.466750
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_limit > 0', name='ck_budgets_limit_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_budgets_user_category')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'partial', 'failed')", name='ck_uploads_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_index('ix_uploads_user_id_content_sha256', 'uploads', ['user_id', 'content_sha256'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'result_type', name='uq_analysis_results_upload_type')
    )
    op.create_index(op.f('ix_analysis_results_upload_id'), 'analysis_results', ['upload_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("module IN ('categorization', 'forecast', 'anomaly', 'summary')", name='ck_analysis_runs_module'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='ck_analysis_runs_status'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'module', name='uq_analysis_runs_upload_module')
    )
    op.create_index(op.f('ix_analysis_runs_upload_id'), 'analysis_runs', ['upload_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_category', sa.String(length=100), nullable=True),
    sa.Column('predicted_category', sa.String(length=100), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_category', sa.String(length=100), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('anomaly_rank', sa.Integer(), nullable=True),
    sa.Column('anomaly_review_status', sa.String(length=20), server_default='unreviewed', nullable=False),
    sa.CheckConstraint("anomaly_review_status IN ('unreviewed', 'confirmed', 'dismissed')", name='ck_transactions_review_status'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_upload_id'), 'transactions', ['upload_id'], unique=False)
    op.create_index('ix_transactions_upload_id_transaction_date', 'transactions', ['upload_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_upload_id_transaction_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_upload_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_analysis_runs_upload_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_analysis_results_upload_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_uploads_user_id_content_sha256', table_name='uploads')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
