"""one active upload per user

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 12:00:38.688663
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_uploads_one_active_per_user', 'uploads', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_uploads_one_active_per_user', table_name='uploads', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    # ### end Alembic commands ###
