"""durable job queue columns and inputs

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 21:50:44.071782
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_inputs',
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.add_column('uploads', sa.Column('claimed_by', sa.String(length=100), nullable=True))
    op.add_column('uploads', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('uploads', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('uploads', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.create_index('ix_uploads_processing_heartbeat', 'uploads', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'processing'"))
    op.create_index('ix_uploads_queued', 'uploads', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uploads_queued', table_name='uploads', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('ix_uploads_processing_heartbeat', table_name='uploads', postgresql_where=sa.text("status = 'processing'"))
    op.drop_column('uploads', 'request_id')
    op.drop_column('uploads', 'attempts')
    op.drop_column('uploads', 'heartbeat_at')
    op.drop_column('uploads', 'claimed_by')
    op.drop_table('upload_inputs')
    # ### end Alembic commands ###
